services:
  admin-service:
    build: ./admin_service/.
    volumes:
      - static_volume:/data/static
      - media_volume:/data/media
    expose:
      - "8000"
    env_file:
      - ./admin_service/.env
    depends_on:
      theatre-db:
        condition: service_healthy
    restart: always


  api-service:
    build: ./api_service/.
    env_file:
      - ./api_service/.env
    depends_on:
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always

  auth-service:
    build: ./auth_service/.
    env_file:
       - ./auth_service/.env
    command: >
      sh -c "alembic upgrade head &&
        gunicorn src.main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8001 --timeout 120"
    volumes:
      - ./auth_service:/app
    depends_on:
      auth-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - static_volume:/data/static
      - media_volume:/data/media   
    depends_on:
      - api-service
    ports:
      - "81:80"
    restart: always
    ulimits:
      nofile:
        soft: 16384
        hard: 16384

  elasticsearch:
    image: elasticsearch:8.19.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - path.repo=/mnt/backups/elasticsearch
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - ./elastic/elastic_backup:/mnt/backups/elasticsearch
      - ./elastic/init.sh:/usr/local/bin/init-elasticsearch.sh:ro
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    command: >
      bash -c '
        /usr/local/bin/docker-entrypoint.sh eswrapper &
        pid=$!;
        sleep 5;
        bash /usr/local/bin/init-elasticsearch.sh;
        wait $pid
      '
      
  redis:
    image: redis:8.2.2
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"

  auth-db:
    image: postgres:17
    env_file:
       - ./auth_service/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      retries: 20
    restart: always
    ports:
      - "5433:5432"

  theatre-db:
    image: postgres:17
    env_file:
       - ./admin_service/.env
    volumes:
      - theatre_postgres_data:/var/lib/postgresql/data
      - ./admin_service/database_dump.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      retries: 10
    restart: always
    ports:
      - "5434:5432"

volumes:
  elasticsearch_data:
  redis_data:
  postgres_data:
  theatre_postgres_data:
  static_volume:
  media_volume: